### ISSUE TITLE
Recommendation: Simplify App.js

### ISSUE THREAD

**Issue by melissamcewen** [madhuinfos/Jamming#2]
I this App.js could be a bit simpler which would improve readability and prevent errors. For example you have your props defined outside the component and they are nested 2 levels in:
https://github.com/madhuinfos/Jamming/blob/master/src/Components/App/App.js#L9-L12

I'd recommend defining them this way 
```
    this.state = {
      searchResults: [],
      playlistName: 'New Playlist',
      playlistTracks: []
    };
```

the effect of the extra complication is that it makes the rest of the code more complicated. Like the solution code I have is 83 lines vs. your app.js is 99. 

Some other simplifications would be getting rid of the spread operator where it isn't needed 
https://github.com/madhuinfos/Jamming/blob/master/src/Components/App/App.js#L48
more info about when this should be used here 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator

and taking advantage of methods like filter here
```javascript
  removeTrack(track) {
    let tracks = this.state.playlistTracks;
    tracks = tracks.filter(currentTrack => currentTrack.id !== track.id);

    this.setState({playlistTracks: tracks});
  }
```
more info about filter
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

I also recommend `const` over `let` https://medium.com/javascript-scene/javascript-es6-var-let-or-const-ba58b8dcde75

attached is the full solution code for app.js
```javascript
import React from 'react';
import './App.css';

import Playlist from '../Playlist/Playlist';
import SearchBar from '../SearchBar/SearchBar';
import SearchResults from '../SearchResults/SearchResults';
import Spotify from '../../util/Spotify';

class App extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      searchResults: [],
      playlistName: 'New Playlist',
      playlistTracks: []
    };

    this.search = this.search.bind(this);
    this.addTrack = this.addTrack.bind(this);
    this.removeTrack = this.removeTrack.bind(this);
    this.updatePlaylistName = this.updatePlaylistName.bind(this);
    this.savePlaylist = this.savePlaylist.bind(this);
  }

  search(term) {
    Spotify.search(term).then(searchResults => {
      this.setState({searchResults: searchResults});
    });
  }

  addTrack(track) {
    let tracks = this.state.playlistTracks;
    if (tracks.find(savedTrack => savedTrack.id === track.id)) {
      return;
    }

    tracks.push(track);
    this.setState({playlistTracks: tracks});
  }

  removeTrack(track) {
    let tracks = this.state.playlistTracks;
    tracks = tracks.filter(currentTrack => currentTrack.id !== track.id);

    this.setState({playlistTracks: tracks});
  }

  updatePlaylistName(name) {
    this.setState({playlistName: name});
  }

  savePlaylist() {
    const trackUris = this.state.playlistTracks.map(track => track.uri);
    Spotify.savePlaylist(this.state.playlistName, trackUris).then(() => {
      this.setState({
        playlistName: 'New Playlist',
        playlistTracks: []
      });
    });
  }

  render() {
    return (
      <div>
        <h1>Ja<span className="highlight">mmm</span>ing</h1>
        <div className="App">
          <SearchBar onSearch={this.search} />
          <div className="App-playlist">
            <SearchResults searchResults={this.state.searchResults}
                           onAdd={this.addTrack} />
            <Playlist playlistTracks={this.state.playlistTracks}
                      onNameChange={this.updatePlaylistName}
                      onRemove={this.removeTrack}
                      onSave={this.savePlaylist} />
          </div>
        </div>
      </div>
    );
  }
}

export default App;

```

**Comment by madhuinfos** [comment]
Thanks for the feedback. Please find the comments
you have your props defined outside the component and they are nested 2 levels in:
- This is done for the sample data will move it inside.
And agree with other comments.

The reason being playlist is kept as a single object, logically play list name & tracks represents a single object. And in future if we want to work with multiple playlist it will be easy to handle. let me know if you think otherwise.
Thanks.
