### ISSUE TITLE
Recommendation: remove .js from imports

### ISSUE THREAD

**Issue by melissamcewen** [madhuinfos/Jamming#4]
One neat trick is you can make your imports more neat by just removing the `.js`
https://github.com/madhuinfos/Jamming/blob/master/src/Components/App/App.js#L3
like it works as
```
import SearchBar from '../SearchBar/SearchBar';

```

**Comment by madhuinfos** [comment]
Hi mellisa,
Thanks for the feedback. Updated the code & committed.
